# Generated by Django 5.0.2 on 2026-06-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("password_reset", "Password Reset"),
                    ("email_change", "Email Change"),
                ],
                max_length=20,
            ),
        ),
    ]
