# Generated by Django 5.0.2 on 2026-06-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customuser_full_name_alter_otpverification_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("password_reset", "Password Reset"),
                    ("email_change", "Email Change"),
                    ("account_delete", "Account Deletion"),
                ],
                max_length=20,
            ),
        ),
    ]
