# Generated by Django 6.0.5 on 2026-06-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_category_product_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="uniq_active_category_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("slug",),
                name="uniq_active_category_slug",
            ),
        ),
    ]
