# Generated by Django 6.0.5 on 2026-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_category_name_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="uniq_active_category_slug",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
