# Generated by Django 6.0.5 on 2026-06-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_material_remove_product_price_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="strap_material",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="case_material",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="case_color",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="dial_color",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="strap_color",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="carry_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tote", "Tote Bag"),
                    ("shoulder", "Shoulder Bag"),
                    ("crossbody", "Crossbody Bag"),
                    ("tophandle", "Top Handle Bag"),
                    ("clutch", "Clutch"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="closure_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zipper", "Zipper"),
                    ("magnetic", "Magnetic Snap"),
                    ("turnlock", "Turn Lock"),
                    ("opentop", "Open Top"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="compartments",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="country_of_origin",
            field=models.CharField(
                blank=True,
                choices=[("india", "India"), ("italy", "Italy"), ("france", "France")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="depth_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="dust_bag_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("leather", "Leather"),
                    ("calfskin", "Calfskin Leather"),
                    ("pebbled", "Pebbled Leather"),
                    ("saffiano", "Saffiano Leather"),
                    ("canvas", "Canvas"),
                    ("vegan", "Vegan Leather"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plain", "Plain"),
                    ("quilted", "Quilted"),
                    ("printed", "Printed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="warranty",
            field=models.CharField(
                blank=True,
                choices=[("none", "No Warranty"), ("6m", "6 Months"), ("1y", "1 Year")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="weight_g",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="width_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Material",
        ),
    ]
