# Generated by Django 5.0.2 on 2026-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_productvariant_strap_material_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="carry_style",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="country_of_origin",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="dust_bag_included",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="warranty",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="weight_g",
        ),
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
