# Generated by Django 5.0.2 on 2026-06-10 09:32

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_MATERIALS = [
    "Leather", "Calfskin Leather", "Pebbled Leather",
    "Saffiano Leather", "Canvas", "Vegan Leather",
]


def seed_materials(apps, schema_editor):
    Material = apps.get_model("core", "Material")
    for name in DEFAULT_MATERIALS:
        Material.objects.get_or_create(name=name)


def unseed_materials(apps, schema_editor):
    Material = apps.get_model("core", "Material")
    Material.objects.filter(name__in=DEFAULT_MATERIALS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_productvariant_carry_style_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_materials, unseed_materials),
        migrations.AddField(
            model_name="productvariant",
            name="color_hex",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="material",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="core.material",
            ),
        ),
    ]
