# Generated by Django 5.0.2 on 2026-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_material_productvariant_color_hex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="depth_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="width_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
