# Generated by Django 5.0.2 on 2026-06-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_cart_cartitem_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="closure_type",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
