# Generated by Django 5.0.2 on 2026-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_closure_type_free_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
