# Generated by Django 5.0.2 on 2026-06-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_product_featured_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="closure_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zipper", "Zipper"),
                    ("magnetic", "Magnetic Snap"),
                    ("drawstring", "Drawstring"),
                    ("flap", "Flap"),
                    ("turnlock", "Turn Lock"),
                    ("opentop", "Open Top"),
                    ("buckle", "Buckle"),
                ],
                max_length=20,
            ),
        ),
    ]
