# Generated by Django 6.0.5 on 2026-06-15 17:50

import django.db.models.deletion
from django.db import migrations, models


def backfill_wishlist_variant(apps, schema_editor):
    """Point each existing wishlist row at its product's default variant."""
    Wishlist = apps.get_model("core", "Wishlist")
    ProductVariant = apps.get_model("core", "ProductVariant")
    for item in Wishlist.objects.filter(variant__isnull=True).select_related("product"):
        variant = (
            ProductVariant.objects.filter(
                product_id=item.product_id, is_default=True, is_deleted=False
            ).first()
            or ProductVariant.objects.filter(
                product_id=item.product_id, is_deleted=False
            ).first()
        )
        if variant:
            item.variant_id = variant.id
            item.save(update_fields=["variant"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_productvariant_closure_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wishlisted_by",
                to="core.productvariant",
            ),
        ),
        migrations.RunPython(backfill_wishlist_variant, noop),
    ]
