# Generated by Django 6.0.5 on 2026-06-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_wishlist_variant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "variant")},
        ),
    ]
