# Generated by Django 6.0.5 on 2026-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_orderstatusevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_return_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="return_reason",
            field=models.TextField(blank=True),
        ),
    ]
