# Generated by Django 6.0.5 on 2026-06-22 14:49

import django.db.models.deletion
from django.db import migrations, models


ITEM_STATUS_CHOICES = [
    ("pending", "Pending"),
    ("confirmed", "Confirmed"),
    ("processing", "Processing"),
    ("shipped", "Shipped"),
    ("out_for_delivery", "Out for Delivery"),
    ("delivered", "Delivered"),
    ("cancelled", "Cancelled"),
    ("return_requested", "Return Requested"),
    ("returned", "Returned"),
]


def populate_item_status(apps, schema_editor):
    """Derive each item's new `status` from its old booleans + the order's status,
    before the boolean columns are dropped."""
    OrderItem = apps.get_model("core", "OrderItem")
    for item in OrderItem.objects.select_related("order").all():
        if item.is_cancelled:
            item.status = "cancelled"
        elif item.is_returned:
            item.status = "returned"
        elif item.is_return_requested:
            item.status = "return_requested"
        else:
            # All legacy order statuses are also valid item statuses.
            item.status = item.order.status or "pending"
        item.save(update_fields=["status"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_orderitem_cancellation_reason_and_more"),
    ]

    operations = [
        # 1. Add the new status field (default pending).
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=ITEM_STATUS_CHOICES,
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        # 2. Populate it from the existing booleans + order status.
        migrations.RunPython(populate_item_status, noop),
        # 3. Now the booleans are safe to drop.
        migrations.RemoveField(model_name="orderitem", name="is_cancelled"),
        migrations.RemoveField(model_name="orderitem", name="is_return_requested"),
        migrations.RemoveField(model_name="orderitem", name="is_returned"),
        # 4. Per-item timeline support on the event model.
        migrations.AddField(
            model_name="orderstatusevent",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_events",
                to="core.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatusevent",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_events",
                to="core.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatusevent",
            name="status",
            field=models.CharField(choices=ITEM_STATUS_CHOICES, max_length=20),
        ),
    ]
