# Generated by Django 6.0.5 on 2026-06-23 05:59

from django.db import migrations, models


def processing_to_packed(apps, schema_editor):
    """The old 'processing' status was renamed to 'packed'."""
    OrderItem = apps.get_model("core", "OrderItem")
    OrderStatusEvent = apps.get_model("core", "OrderStatusEvent")
    OrderItem.objects.filter(status="processing").update(status="packed")
    OrderStatusEvent.objects.filter(status="processing").update(status="packed")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_orderitem_is_cancelled_and_more"),
    ]

    operations = [
        migrations.RunPython(processing_to_packed, noop),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("returned", "Returned"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatusevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("returned", "Returned"),
                ],
                max_length=20,
            ),
        ),
    ]
