# Generated by Django 6.0.5 on 2026-06-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_orderitem_status_alter_orderstatusevent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="return_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="return_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                    ("returned", "Returned"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatusevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                    ("returned", "Returned"),
                ],
                max_length=20,
            ),
        ),
    ]
