# Generated by Django 6.0.5 on 2026-06-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_orderitem_status_alter_orderstatusevent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
