# Generated by Django 6.0.5 on 2026-06-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_backfill_orderitem_original_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("razorpay", "Razorpay (Online)"),
                ],
                default="COD",
                max_length=20,
            ),
        ),
    ]
