# Generated by Django 6.0.5 on 2026-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("razorpay", "Razorpay (Online)"),
                    ("wallet", "Wallet"),
                ],
                default="COD",
                max_length=20,
            ),
        ),
    ]
