# Generated by Django 5.0.2 on 2026-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_order_coupon_order_coupon_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
