# Generated by Django 5.0.2 on 2026-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_review_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_hidden",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
