# Generated by Django 5.0.2 on 2026-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_review_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_file",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
    ]
