# Generated by Django 6.0.5 on 2026-07-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_orderitem_status_alter_orderstatusevent_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                    ("pickup_scheduled", "Pickup Scheduled"),
                    ("return_picked", "Return Picked"),
                    ("returned", "Returned"),
                    ("return_repair", "Sent for Repair"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_pending", "Payment Pending"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatusevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                    ("pickup_scheduled", "Pickup Scheduled"),
                    ("return_picked", "Return Picked"),
                    ("returned", "Returned"),
                    ("return_repair", "Sent for Repair"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_pending", "Payment Pending"),
                ],
                max_length=20,
            ),
        ),
    ]
