# Generated by Django 6.0.5 on 2026-06-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("global", "All Products (Global)"),
                    ("specific", "Specific Products/Categories"),
                ],
                default="global",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="first_time_only",
            field=models.BooleanField(
                default=False, help_text="Only for first-time users"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="payment_methods",
            field=models.CharField(blank=True, default="all", max_length=50),
        ),
        migrations.AddField(
            model_name="coupon",
            name="per_user_limit",
            field=models.PositiveIntegerField(
                default=0, help_text="0 = unlimited per user"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="title",
            field=models.CharField(
                blank=True, help_text="Display name for this coupon", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("flat", "Fixed Amount (₹)")],
                default="percentage",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
        ),
    ]
