# Generated by Django 6.0.5 on 2026-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_order_coupon_order_coupon_discount"),
        ("coupons", "0002_coupon_applies_to_coupon_first_time_only_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="specific_categories",
            field=models.ManyToManyField(
                blank=True, related_name="coupons", to="core.category"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="specific_products",
            field=models.ManyToManyField(
                blank=True, related_name="coupons", to="core.product"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("global", "All Products (Global)"),
                    ("specific_products", "Specific Products"),
                    ("specific_categories", "Specific Categories"),
                ],
                default="global",
                max_length=20,
            ),
        ),
    ]
