# Generated by Django 5.0.2 on 2026-06-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("global", "Global Offer"),
                    ("product", "Product Offer"),
                    ("category", "Category Offer"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
