# Generated by Django 5.0.2 on 2026-07-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="sub_type",
            field=models.CharField(
                choices=[
                    ("refund", "Refund"),
                    ("topup", "Top Up"),
                    ("order", "Order"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=10,
            ),
        ),
    ]
